FROM oracle/graalvm-ce:20.2.0-java8 as graalvm
RUN gu install native-image

COPY . /home/app/app
WORKDIR /home/app/app

RUN native-image -cp target/app-*.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/app/app /app/app
ENTRYPOINT ["/app/app"]

